### ISSUE TITLE
Compatability with Realsense D415

### ISSUE THREAD

**Issue by vincent-mayer** [pal-robotics/realsense_gazebo_plugin#23]
Hey,
first of all great work, much appreciated! I would like to know, whether this plugin would work with the Intel Realsense D415 also? After a first look, I could not find any good reason why it would not (given the corresponding D415 Gazebo / URDF files), is that correct?

**Comment by v-lopez** [comment]
I 'd think so. Mostly you'll have to adjust the FoV of the D415. 

I don't have a D415 to test, I'm not sure if they publish the same topics.

**Comment by vincent-mayer** [comment]
Thanks! I'll try it out and report the results here. Will close the issue for now.
