### ISSUE TITLE
realsense plugin for the ignition (gazebo)

### ISSUE THREAD

**Issue by addy1997** [pal-robotics/realsense_gazebo_plugin#34]
Hello there,

I have made some changes in the code of this plugin to make it compatible with the [ignition gazebo](https://github.com/ignitionrobotics/ign-gazebo). The source code can be found [here](https://github.com/addy1997/ignition-plugins/tree/dev/realsense_camera) with the [CMakeLists.txt file](https://github.com/addy1997/ignition-plugins/blob/dev/realsense_camera/CMakeLists.txt) to compile it. 

How can I contribute to your project?

**Comment by v-lopez** [comment]
If you are still intesrested, you could create a merge request.

I'd have to check how are other gazebo/ignition plugin repositories structured.

**Comment by addy1997** [comment]
@v-lopez Yes, I am interested. I have opened the pull request.

**Comment by addy1997** [comment]
@v-lopez, any updates?

**Comment by v-lopez** [comment]
I've been reviewing how ignition plugins are handled. It looks like they are in completely separated repositories, so it makes no sense to host them here.

I apologise for making you spend time on the PR.
