### ISSUE TITLE
Realsense D435 Gazebo Model

### ISSUE THREAD

**Issue by MoTahoun** [pal-robotics/realsense_gazebo_plugin#4]
Hello, 
Do you have the gazebo model for the intel real sense d435? or how do you tested it?
Is it possible to supply an example or a  tutorial on how to use the plugin?

Thanks in advance and waiting for your response.

Regards,

**Comment by saikishor** [comment]
@MoTahoun You can find the information on the URDF and the respective gazebo xacro files here : https://github.com/pal-robotics-forks/realsense/tree/upstream

**Comment by MoTahoun** [comment]
@saikishor It's amazing. I managed to make working properly with multiple cameras. Thanks again
